apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3478
      protocol: UDP
      name: turn
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
